# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgxcli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "d456565eeec52c49271055eec38eb75dc7fa7b307578ce08399ea55eabcbfbec"
      url "https://github.com/Balaji01-4D/pgxcli/releases/download/v#{version}/pgxcli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6050832581bd42bd6fbfa2eb266b371c0675fabc474589c34cf6560e6dfbf3c3"
      url "https://github.com/Balaji01-4D/pgxcli/releases/download/v#{version}/pgxcli_Darwin_arm64.tar.gz"
    end
  end

  name "pgxcli"
  desc "An interactive PostgreSQL CLI written in Go"
  homepage "https://github.com/Balaji01-4D/pgxcli"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "less",
    ]

  binary "pgxcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pgxcli"]
    end
  end

  # No zap stanza required

end
