# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgxcli < Formula
  desc "Interactive PostgreSQL command-line client written in Go."
  homepage "https://pgxcli.vercel.app/"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Balaji01-4D/pgxcli/releases/download/v0.2.0/pgxcli_0.2.0_darwin_amd64.tar.gz"
    sha256 "243b34e7a875f8c181d6092ce49577a729271e8ea2463f4d73a90233c8428bb2"

    define_method(:install) do
      bin.install "pgxcli"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Balaji01-4D/pgxcli/releases/download/v0.2.0/pgxcli_0.2.0_darwin_arm64.tar.gz"
    sha256 "593d6f4ff01ac26c52a645e298cd0034a743d9676c20c441bbe74ed509b0f119"

    define_method(:install) do
      bin.install "pgxcli"
    end
  end

  test do
    system "#{bin}/pgxcli --version"
  end
end
